latex-indent: latex-indent.o
	gcc -o latex-indent latex-indent.o -Wall -Wextra -Werror -g

latex-indent.o: latex-indent.c
	gcc -o latex-indent.o -c latex-indent.c -Wall -Wextra -Werror -g

clean:
	rm -f *.o latex-indent